---
- set_fact:
    pip_exe: "{{ miniconda_home }}/envs/prod/bin/pip"
    conda_exe: "{{ miniconda_home }}/envs/prod/bin/conda"

- name: install conda dependencies
  shell: "{{ conda_exe }} install --yes --file {{ install_dir }}/requirements/conda.txt"

- name: install packages
  pip: executable="{{ pip_exe }}" extra_args="--editable"
       name="{{ install_dir }}"

- name: install dev dependencies
  pip: executable="{{ pip_exe }}"
       requirements={{ install_dir }}/requirements/dev.txt
